name: three-gen-judge
channels:
  - defaults
  - nvidia
  - conda-forge
  - pytorch

dependencies:
  - python=3.11
  - pip
  - cuda-toolkit=12.6
  - gcc=12.4
  - gxx=12.4
  - pip:
      - -r requirements.txt
