name: three-gen-validation
channels:
  - defaults
  - conda-forge
  - nvidia
  
dependencies:
  - python=3.10
  - pip
  - cuda-toolkit=12.1.1
  - cudnn=8.9.7
  - gcc=11.4
  - gcc_linux-64=11.4
  - pip:
    - -r requirements.txt
