name: three-gen-validation
channels:
  - defaults
  - conda-forge
  - nvidia
  
dependencies:
  - python=3.10
  - pip
  - cuda-toolkit=12.1.1
  - cudnn=8.9.7
  - gcc=11.4
  - gcc_linux-64=11.4
  - mesa-libegl-devel-cos7-x86_64=18.3.4
  - mesa-libgl-devel-cos7-x86_64=18.3.4
  - libglvnd-devel-cos7-x86_64=1.0.1
  - libpq=16.1
  - pip:
    - h5py==3.10.0
    - numpy==1.22.4
    - tqdm==4.65.2
    - scipy==1.11.4
    - pillow==10.2.0
    - torch==2.1.1
    - transformers==4.36.2
    - open-clip-torch==2.24.0
    - pytest==8.1.1
    - bittensor==6.9.3

