name: three-gen-validation
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - gcc=13.2
  - gxx=13.2
  - lld=20.1.8
  - cmake=3.31.4
  - ninja=1.12.1
  - zstd=1.5.7
  - pybind11=2.13.6
  - cuda-toolkit=12.8.0
  - cudnn=9.3.0.75
  - pytorch=2.7.0
  - torchmetrics=1.8.0
  - pip:
      - -r requirements.txt

variables:
  CUDA_HOME: "$CONDA_PREFIX"
  CPATH: "$CONDA_PREFIX/targets/x86_64-linux/include:$CONDA_PREFIX/include"
  LD_LIBRARY_PATH: "$CONDA_PREFIX/targets/x86_64-linux/lib:$CONDA_PREFIX/lib"
