name: three-gen-mining
channels:
  - defaults
  - conda-forge
  - nvidia
  
dependencies:
  - python=3.10
  - pip
  - cuda-toolkit=12.1
  - cudnn=8.9
  - gcc=11.4
  - gxx=11.4
  - libxcrypt
  - pip:
    - -r requirements.txt